[dev] cpathc / cmake foo to run tests on rook

diff --git a/src/script/cpatch b/src/script/cpatch
--- a/src/script/cpatch
+++ b/src/script/cpatch
@@ -9,7 +9,7 @@ if [ ! -e Makefile ] && [ ! -e build.ninja ] || [ ! -e ../do_cmake.sh ]; then
     exit 1
 fi
 
-base="quay.ceph.io/ceph-ci/ceph:master"
+base="quay.io/ceph-ci/ceph:master"
 target=""
 push=0
 strip=1
@@ -94,14 +94,16 @@ if [ -z "$target" ]; then
     exit 1
 fi
 
-if [ -x /usr/bin/podman ]; then
-    runtime="podman"
-elif [ -x /usr/bin/docker ]; then
-    runtime="docker"
-else
-    echo "cannot find podman or docker in PATH"
-    exit 1
-fi
+# if [ -x /usr/bin/podman ]; then
+#     runtime="podman"
+# elif [ -x /usr/bin/docker ]; then
+#     runtime="docker"
+# else
+#     echo "cannot find podman or docker in PATH"
+#     exit 1
+# fi
+
+runtime="docker"
 
 TMP="$BUILDPATH/tmp.cpatch"
 if [ -d $TMP ]; then rm -rf $TMP ; fi
@@ -134,7 +136,7 @@ if [ $py -eq 1 ] || [ $all -eq 1 ]; then
     # Exclude node_modules because it's the huge sources in dashboard/frontend
     tar --exclude=node_modules --exclude=tests --exclude-backups -cf $TMP/python_common.tar *
     popd > /dev/null
-    dockerfile+=$'ADD python_common.tar /usr/lib/python3.8/site-packages\n'
+    dockerfile+=$'ADD python_common.tar /usr/lib/python3.6/site-packages\n'
 
     pushd lib/cython_modules/lib.3
     CYTHONLIBS="*.cpython-3*.so"
@@ -142,7 +144,7 @@ if [ $py -eq 1 ] || [ $all -eq 1 ]; then
     for f in $CYTHONLIBS; do cp $f $TMP/cythonlib ; done
     [ $strip -eq 1 ] && strip $TMP/cythonlib/*
     popd > /dev/null
-    dockerfile+=$'ADD cythonlib /usr/lib64/python3.8/site-packages\n'
+    dockerfile+=$'ADD cythonlib /usr/lib64/python3.6/site-packages\n'
 
     # cephadm
     pushd ../src/cephadm > /dev/null
@@ -160,12 +162,13 @@ if [ $core -eq 1 ] || [ $all -eq 1 ]; then
     mkdir -p $TMP/bin
     for f in $BINS; do cp bin/$f $TMP/bin ; done
     [ $strip -eq 1 ] && strip $TMP/bin/*
+    cp bin/ceph $TMP/bin
     dockerfile+=$'ADD bin /usr/bin\n'
 
     # We need ceph-common to support the binaries
     # We need librados/rbd to support mgr modules
     # that import the python bindings
-    LIBS="libceph-common.so.2 libceph-common.so librados.so.2 librados.so librados.so.2.0.0"
+    LIBS="libceph-common.so.2 libceph-common.so librados.so.2 librados.so librados.so.2.0.0 libcephsqlite.so"
     mkdir -p $TMP/lib
     for f in $LIBS; do cp lib/$f $TMP/lib ; done
     [ $strip -eq 1 ] && strip $TMP/lib/*
